### ISSUE TITLE
The queried repository has too many forks 

### ISSUE THREAD

**Issue by stdedos** [useful-forks/useful-forks.github.io#13]
I have hit this unfortunate message
> It's also possible that the queried repository has so many forks that it's impossible to scan it completely without running out of API calls. :(

while scanning https://github.com/dbeaver/dbeaver.

I would gladly give up some Local Storage in order to be able to fully scan a repo.

I will just give my whole thought process, even though it might be complicated to do it in one go:

1. Keep API calls counter #7, number of API calls still available, and API limit refresh time
2. Store all inactive forks in a cache for a some time (e.g. 1 week).
   Add a tooltip on the side of the page "Skipping x number of forks because they are empty [reset cache]"
3. When the number of API calls still available is zero, start the API limit refresh timer as a countdown
4. Store the current results in cache, with their fetch timestamp (e.g. for 1 day)
5. Add/Enable a button [continue fetching] when the [API limit refresh time reaches zero | it is detected that there are API calls available]

and lastly,

I don't know how feasible it is (it doesn't look like it), but server-side caching shouldn't be too much (I don't think that table would be too much to store as JSON), and might help "fight" the scourge empty forks.

**Comment by payne911** [comment]
Yes, this is a very unfortunate limitation of the tool. I contacted GitHub to try to figure out what can be done, but so far it seems like there isn't an easy solution.

The problem is that I don't really have access to a persistence layer (the server-side statefulness you talk about): the website is just a static page generated by GitHub's servers. The only persistence we can do is locally.

The easiest solution I can think of would be to stall the API Requests for a whole hour when the limit is reached. Then, when that countdown would expire, the algorithm could keep running from where it paused at.

Another potential solution would be to include more optional URL parameters which would guide the algorithm in terms of where it begins its scan, but that's also prone to error and a clumsy implementation.

But I think the real question here is: are users really willing to learn a (rather frustrating and cumbersome) process to complete their forks-scan? Anything that involves a "please come back later" solution sounds like it isn't necessarily worth coding.

**Comment by stdedos** [comment]
> But I think the real question here is: are users really willing to learn a (rather frustrating and cumbersome) process to complete their forks-scan? Anything that involves a "please come back later" solution sounds like it isn't necessarily worth coding.

I never talked about "users learning", but yeah - maybe it's indeed too much.

Let's leave it float until people start discovering this more.

**Comment by payne911** [comment]
Alright, so I have been thinking a bit more about this: I think there is a way to integrate your idea in a sufficiently nice way.

---

### UI proposal
We'd be talking about a new icon at the top-right, in the header nav-bar: a little bell icon with a red notification number that would indicate how many interrupted scans are stored in the local cache. When clicking on the icon, it should open either a small notification modal dialog just below the icon, or a sliding partial modal dialog coming from the right-side of the screen.

That modal dialog should display clickable regions containing information about the interrupted scans. Clicking the regions would launch the saved search parameter.

### The cache
* I think the cache itself should be a new file in [`docs/src`](https://github.com/useful-forks/useful-forks.github.io/tree/master/docs/src)
* The [`add_fork_elements`](https://github.com/useful-forks/useful-forks.github.io/blob/master/docs/src/queries-logic.js#L206) function would be modified to call the stored cache.
* Maybe it would be nice to provide an option for users to clear it on demand?

---

### Rate-Limit considerations
But I also made a little bit of research to see how the Rate Limit could be increased. Here is what I found:
* Using REST calls is the probably the biggest error. I'm not very familiar with GraphQL, but from what I understand [its Rate-Limit is calculated differently](https://docs.github.com/en/graphql/overview/resource-limitations#rate-limit). Making the switch would probably be extremely beneficial (and I think it would even resolve [this old issue](https://github.com/useful-forks/useful-forks.github.io/issues/2)).
* I'm [currently exploring](https://github.community/t/github-apps-rate-limiting-for-client-rest-calls/164336?u=payne911) how applying for a [GitHub Apps](https://docs.github.com/en/developers/apps/differences-between-github-apps-and-oauth-apps#token-based-identification) might actually increase the limit.
* The GitHub API provides [conditional requests](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests) which could take advantage of *their* server-side caching.
* Calls to the [`GET Rate-Limit` endpoint](https://docs.github.com/en/rest/reference/rate-limit#get-rate-limit-status-for-the-authenticated-user) do not count against the REST API rate-limit.

**Comment by stdedos** [comment]
All sound awesome to me. Unfortunately, you will not be able to solve #7 cleanly (as GraphQL uses a "normalized score" and does not count "API requests"), but that's a very small problem.

**Comment by payne911** [comment]
As it was determined [in another issue](https://github.com/useful-forks/useful-forks.github.io/issues/7#issuecomment-787004624), this problem actually concerns GitHub API's abuse detection mechanism due to how fast the tool sends requests (indeed, this problem arises before even reaching 10% of the allowed rate-limit).

I created [a thread on the GitHub Forum](https://github.community/t/what-are-the-rules-behind-you-have-triggered-an-abuse-detection-mechanism/164457), hopefully we can get more answers there.

**Comment by payne911** [comment]
Update: I started a PoC to try out `octokit` and see if it could help with reaching the actual 5000 requests per hour Rate Limit.

**Comment by payne911** [comment]
@stdedos Alright, I just finished making a very basic proof-of-concept which uses `octokit` to issue requests.

---

# Result
For the `dbeaver/dbeaver` repo query, I now reach `1783 calls` before my current (flimsy) code just stalls.

![image](https://user-images.githubusercontent.com/38117856/109445884-8dad2e80-7a0e-11eb-922d-3e041998be5c.png)

---

# Oddities
I did notice a few oddities. Here are a few examples:

## No common ancestor (`404`)
[`WrenchSQL/dbeaver`](https://github.com/WrenchSQL/dbeaver) fork (request URL is: `https://api.github.com/repos/dbeaver/dbeaver/compare/devel...WrenchSQL%3Adevel`):

```
{
  "message": "No common ancestor between devel and WrenchSQL:devel.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#compare-two-commits"
}
```

![image](https://user-images.githubusercontent.com/38117856/109446727-33ad6880-7a10-11eb-93fb-22837dc30268.png)

## Not Found (`404`)
[`lodice/dbeaver`](https://github.com/lodice/dbeaver) fork (request URL is: `https://api.github.com/repos/dbeaver/dbeaver/compare/devel...lodice%3Adevel`):

```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#compare-two-commits"
}
```

<details>
  <summary><b><i>Click to see the fork object that was part of the `GET Forks` response array</i></b></summary>

```json
  {
    "id": 180952855,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODA5NTI4NTU=",
    "name": "dbeaver",
    "full_name": "lodice/dbeaver",
    "private": false,
    "owner": {
      "login": "lodice",
      "id": 49549870,
      "node_id": "MDQ6VXNlcjQ5NTQ5ODcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/49549870?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lodice",
      "html_url": "https://github.com/lodice",
      "followers_url": "https://api.github.com/users/lodice/followers",
      "following_url": "https://api.github.com/users/lodice/following{/other_user}",
      "gists_url": "https://api.github.com/users/lodice/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lodice/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lodice/subscriptions",
      "organizations_url": "https://api.github.com/users/lodice/orgs",
      "repos_url": "https://api.github.com/users/lodice/repos",
      "events_url": "https://api.github.com/users/lodice/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lodice/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/lodice/dbeaver",
    "description": "Free universal database tool and SQL client",
    "fork": true,
    "url": "https://api.github.com/repos/lodice/dbeaver",
    "forks_url": "https://api.github.com/repos/lodice/dbeaver/forks",
    "keys_url": "https://api.github.com/repos/lodice/dbeaver/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lodice/dbeaver/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lodice/dbeaver/teams",
    "hooks_url": "https://api.github.com/repos/lodice/dbeaver/hooks",
    "issue_events_url": "https://api.github.com/repos/lodice/dbeaver/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lodice/dbeaver/events",
    "assignees_url": "https://api.github.com/repos/lodice/dbeaver/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lodice/dbeaver/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lodice/dbeaver/tags",
    "blobs_url": "https://api.github.com/repos/lodice/dbeaver/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lodice/dbeaver/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lodice/dbeaver/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lodice/dbeaver/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lodice/dbeaver/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lodice/dbeaver/languages",
    "stargazers_url": "https://api.github.com/repos/lodice/dbeaver/stargazers",
    "contributors_url": "https://api.github.com/repos/lodice/dbeaver/contributors",
    "subscribers_url": "https://api.github.com/repos/lodice/dbeaver/subscribers",
    "subscription_url": "https://api.github.com/repos/lodice/dbeaver/subscription",
    "commits_url": "https://api.github.com/repos/lodice/dbeaver/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lodice/dbeaver/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lodice/dbeaver/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lodice/dbeaver/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/lodice/dbeaver/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lodice/dbeaver/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lodice/dbeaver/merges",
    "archive_url": "https://api.github.com/repos/lodice/dbeaver/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lodice/dbeaver/downloads",
    "issues_url": "https://api.github.com/repos/lodice/dbeaver/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lodice/dbeaver/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lodice/dbeaver/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lodice/dbeaver/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lodice/dbeaver/labels{/name}",
    "releases_url": "https://api.github.com/repos/lodice/dbeaver/releases{/id}",
    "deployments_url": "https://api.github.com/repos/lodice/dbeaver/deployments",
    "created_at": "2019-04-12T07:19:06Z",
    "updated_at": "2019-04-12T07:19:21Z",
    "pushed_at": "2019-04-11T21:53:01Z",
    "git_url": "git://github.com/lodice/dbeaver.git",
    "ssh_url": "git@github.com:lodice/dbeaver.git",
    "clone_url": "https://github.com/lodice/dbeaver.git",
    "svn_url": "https://github.com/lodice/dbeaver",
    "homepage": "http://dbeaver.io",
    "size": 249618,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "devel",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    }
  },
```
</details>

That currently leaves a row which should be removed. I think that specific problem can be fixed in my code. But in any case, I'm puzzled as of why GitHub returns forks which don't seem to exist.

![image](https://user-images.githubusercontent.com/38117856/109447659-26917900-7a12-11eb-9ea9-e7a47d0bc561.png)

**Comment by payne911** [comment]
> while scanning https://github.com/dbeaver/dbeaver

PR #15 fixed the scan for that specific repository (since it was actually an "Abuse Detection Mechanism" that was at play there).

Nonetheless, I'll leave this issue opened because it doesn't solve the real question at stake here: what to do when we try to scan a massive repository which will always reach the Rate Limit provided by GitHub API? An example would be [`libgdx/libgdx`](https://github.com/libgdx/libgdx).

**Comment by payne911** [comment]
I tried both dbeaver/dbeaver and libgdx/libgdx and could reach a full scan without encountering this issue anymore.
I'll close it for now, until someone reports back that they've actually seen this error, and can provide a reproducible repo input.
