### ISSUE TITLE
It doesn't look for parent forks

### ISSUE THREAD

**Issue by fregante** [useful-forks/useful-forks.github.io#17]
This is a fork: https://github.com/anchan828/json-ast
And it has a few parents and siblings, but this page is empty: https://useful-forks.github.io/?repo=anchan828%2Fjson-ast

**Comment by payne911** [comment]
I created #11 for this specific reason. It *is* the currently expected behavior.

I'll close this issue. If you think the behavior should be modified, I think we should discuss that in the issue I linked above.

---

Also, by the way, the fork you pointed out has no siblings, as shown by this full network tree:

![image](https://user-images.githubusercontent.com/38117856/109751804-3db89e00-7bad-11eb-86ee-5322e58dff2a.png)

**Comment by fregante** [comment]
I ended up on that fork so I thought I’d use useful-forks to find the most active fork. I guess you want me to get to the root **first** and then go from there? What’s the point? I think it should just traverse the whole tree regardless of where it starts

**Comment by payne911** [comment]
It really is about having control over where to begin the search, in my opinion. For multiple reasons:
1. We only get at most 5000 calls per hour to the API. Some repositories exhaust that very quickly.
2. Querying and filtering thousands of forks takes time: if the user knows where he wants to begin the search, it's much better that way.
