### ISSUE TITLE
Allow exporting results in at least csv format

### ISSUE THREAD

**Issue by kunaltyagi** [useful-forks/useful-forks.github.io#22]
Nice project :)

Sometimes, it takes a long time to get all results, but the output can't be easily exported.

**Comment by payne911** [comment]
Thank you! :)

I've actually been considering this so that people can share results through a simple URL.

My problem is that there is a maximum length to URLs so it'd be hard to encode very long result lists in there. I'm still trying to land on a viable solution.

If you have any ideas, feel free to share. :)

**Comment by kunaltyagi** [comment]
For now, how about allowing the user to download the data (as csv/markdown)?

Later, you can allow the users to add a paste using their own pastebin account. No need to work with URLs :)

If you want url, then serialize the results, then compress them (lzma?) Might be possible to cover almost all repos (since you also filter results with no modifications on master).

**Comment by payne911** [comment]
For now, after a quick research, I've found a solution which seems to work out-of-the-box, for the most part.

https://stackoverflow.com/a/33807762/9768291

I'll get around to doing something similar at some point when I have time.

**Comment by payne911** [comment]
![csv](https://user-images.githubusercontent.com/38117856/112167712-0b57fa80-8bc7-11eb-8caa-b8215e1eff5f.png)

I started working on this :)
