### ISSUE TITLE
Why is `public_repo` scope requested?

### ISSUE THREAD

**Issue by jack1142** [useful-forks/useful-forks.github.io#30]
It seems like all the used API endpoints only use public data and therefore shouldn't need any scopes.

**Comment by payne911** [comment]
@jack1142 Would you mind trying to create a token which doesn't have that scope and use it to see if the tool still works properly?

**Comment by jack1142** [comment]
It does work from what I can tell - I've only been using useful-forks in that way since it seemed weird to me to require the repo scope for read-only access of public repositories

**Comment by payne911** [comment]
I just tested it out (since GitHub is rolling a new format for the tokens, I wanted to make sure everything still worked) : you are right.

At this point, I'm wondering what the `public_repo` scope is used if not for that kind of use-case.

In any case, I'll update the code. Thanks for pointing this out!

**Comment by jack1142** [comment]
> At this point, I'm wondering what the `public_repo` scope is used for if not for that kind of use-case.

It is used for write access to the repository, stuff that is available without logging in doesn't require any scopes.

**Comment by payne911** [comment]
It just says :

![image](https://user-images.githubusercontent.com/38117856/124368723-c44fbb80-dc31-11eb-90b0-fde8c193ec67.png)

Its name should be more explicit. Anyways, thanks for bringing this to my attention.
