### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by fregante** [useful-forks/useful-forks.github.io#42]

**Comment by payne911** [comment]
If the pop up appears, it's because a token needs to be provided in order to show more results.

Unfortunately, unauthenticated calls get rate limited at a prohibitively low amount of requests. I personally would assume that it is so low that in the great majority of cases where someone might want to use Useful-Forks to analyze a list of forks, it would barely show any relevant results. That is why I think it makes sense to have this process be a bit "intrusive".

However, maybe we could reach a middle-ground: the pop-up could be the default behavior, but a URL parameter could potentially control how that alert gets raised (something like `&popup=false`).

**Comment by fregante** [comment]
I don’t think that makes sense, you don't have to use a popup for this, covering what's already on the page. An banner would be much better

**Comment by payne911** [comment]
Would you expect the link to open that dialog?
What is the gain in requiring an extra click from users?

**Comment by payne911** [comment]
I'm not sure why this user is reacting as they are with regards to this issue. I do believe it's a valid concern, but I just don't have much time to dedicate to fixing it.

My personal view on this is summarized [here](https://github.com/useful-forks/useful-forks.github.io/pull/62#issuecomment-1496209833):

> Please add a URL parameter which can be used to disable the popup. I personally will be keeping the popup as the default behavior for now.
> 
> Also, if the popup isn't displayed, this message banner should be better at directing the user: instead of the part that mentions the button at the top-right, it should contain a text field with the token value in it, and some buttons to create and save. Thus, it would essentially provide the same user experience as the popup. And depending on how that looks and feels, I might consider removing the popup entirely.

**Comment by fregante** [comment]
Your request is different from mine, you can create a dedicated issue

**Comment by payne911** [comment]
lol, this guy is on another level in terms of passive-aggressiveness.

![image](https://user-images.githubusercontent.com/38117856/232235991-83fb4071-c050-400c-af9e-e426f6d63735.png)
