### ISSUE TITLE
ignore forks only having commits like "Merge pull request .. from .."

### ISSUE THREAD

**Issue by Ethkuil** [useful-forks/useful-forks.github.io#52]
Actually there are nothing difference between them and the parent repo. So it would be better if they can be ignored too.

**Comment by payne911** [comment]
Mind showing an example?
My understanding is that if there's an extra commit saying something was merged into master... then there is indeed new content.

**Comment by Ethkuil** [comment]
> Mind showing an example? My understanding is that if there's an extra commit saying something was merged into master... then there is indeed new content.

Not always. For example, just sync with origin.

Actual examples are common. At random I choose a [repo](https://useful-forks.github.io/?repo=xinebf%2Fgoogle-translate-for-goldendict). I really find some useful forks, but useless forks shown are more than useful ones lol.

**Comment by payne911** [comment]
I do not disagree with this as being useful, but I believe analyzing the commit message would unfortunately require an extra API call way too often (something which is already very restrictive with regards to the tool's main purpose).

One imperfect work-around you may use would be to assume that all forks with only 1 commit ahead are useless. When you click the settings clog icon next to the search field, you can then modify this value:

<img width="675" alt="image" src="https://user-images.githubusercontent.com/38117856/205724871-f60e3e3c-e509-4ecf-8878-26727521f6ec.png">

Eventually, I do plan on having some kind of dynamic analysis that would make searches more useful when the amount of forks isn't very high (because then I'm not limited by the amount of API calls as much). But it's mostly a matter of time and motivation before I do end up working on that feature.

**Comment by Ethkuil** [comment]
I understand. And thanks for your work-around!

For me it's better to set `Ahead filter` 1 by default, because I have never see a useful fork with only one ahead commit. And it works great!

**Comment by Ethkuil** [comment]
The limit from GitHub API is really hard to overcome. This is a dilemma "more targeted" versus "more comprehensive".

And maybe we can supply choices like filter by "last updated date", "watch/star"? There can help much when the forks are really really many. In the case certainly it's a big project, therefore we have reason to raise the standard. For example, I would not believe a fork of Linux that last updated in 2011 and no stars could be useful.

**Comment by Ethkuil** [comment]
I would like to have a try for it(about pre-filters before querying commit diff and post-analysis after querying commit diff) next month, and at that time we could continue talking about the design. At least they're helpful for me.

Current idea:
- [ ] Add filter to take effect before appending new rows. The filter can be inputted as a filter expression like `stars:>0 | pushed:>2022-01-01`.
- [ ] If a fork is with only 1 commit head, check whether the commit is a merge or new content. (no idea about how to achieve this).

**Comment by payne911** [comment]
If you are interested in contributing, you might want to look at where the main interests lies. Some features are definitely more requested than others: https://github.com/useful-forks/useful-forks.github.io/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

More in-line with what *you* are interested in, maybe this could help orient you: https://github.com/useful-forks/useful-forks.github.io/issues/37#issuecomment-1338861337
